apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-whoami
  template:
    metadata:
      labels:
        app: traefik-whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: traefik-whoami
spec:
  selector:
    app: traefik-whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---