name: Run Azure Login with OIDC
on: [push]

permissions:
   id-token: write
   contents: read
   actions: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group list

      - name: Gets K8s context
        uses: azure/aks-set-context@v2
        with:
            resource-group: rg-test-2023-09-16
            cluster-name: aks-test-2023-09-16

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
              manifests/whoami.yml
